# Generated by Django 5.2.17 on 2026-09-16 18:42

import common.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_project_section_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='features_image',
            field=models.ImageField(blank=True, upload_to='projects/features/', validators=[common.validators.validate_image]),
        ),
        migrations.AlterField(
            model_name='project',
            name='inquiry_image',
            field=models.ImageField(blank=True, upload_to='projects/inquiries/', validators=[common.validators.validate_image]),
        ),
    ]
