"use client";
/* eslint-disable react-hooks/exhaustive-deps */
import Link from "next/link";
import {FormEvent,useEffect,useState} from "react";
import {useRouter} from "next/navigation";
import {api,User} from "@/lib/api";
import {adminFetch} from "@/lib/admin-api";
import {Icon} from "@/components/icons";

const staffRoles=["SUPER_ADMIN","CONTENT_ADMIN","PROJECT_MANAGER","SALES_OFFICER","SUPPORT_OFFICER"];
export default function Login(){
  const router=useRouter();const[error,setError]=useState("");const[busy,setBusy]=useState(false);
  async function routeForRole(){const r=await adminFetch("/auth/me/");if(!r.ok)return "/login";const b=await r.json();const user=(b.data||b)as User;const requested=new URLSearchParams(window.location.search).get("next");if(requested?.startsWith("/admin-dashboard")&&staffRoles.includes(user.role))return requested;return staffRoles.includes(user.role)?"/admin-dashboard":"/dashboard"}
  useEffect(()=>{if(localStorage.getItem("access_token")||localStorage.getItem("refresh_token"))routeForRole().then(path=>{if(path!=="/login")router.replace(path)})},[]);
  async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError("");const fd=new FormData(e.currentTarget);try{const tokens=await api<{access:string;refresh:string}>("/auth/login/",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({email:fd.get("email"),password:fd.get("password")})});localStorage.setItem("access_token",tokens.access);localStorage.setItem("refresh_token",tokens.refresh);router.push(await routeForRole())}catch(e){setError(e instanceof Error?e.message:"Login failed")}finally{setBusy(false)}}
  return <main className="grid min-h-screen lg:grid-cols-2"><section className="login-image hidden p-12 text-white lg:flex lg:flex-col lg:justify-between"><Link href="/" aria-label="Raha Holdings home"><img src="/images/brand/raha-one-color-white.png" alt="Raha Holdings" className="site-logo"/></Link><div><p className="eyebrow text-gold-light">One secure workspace</p><h1 className="mt-6 max-w-xl font-serif text-6xl leading-tight">Your property world,<br/><i>all in one place.</i></h1><p className="mt-6 max-w-md leading-7 text-white/65">Customers see their private portal. Authorized team members enter the administration workspace automatically.</p></div><p className="text-xs text-white/40">Secure account access</p></section><section className="flex items-center justify-center bg-cream p-6"><div className="w-full max-w-md"><Link href="/" className="mb-14 flex items-center gap-2 text-xs uppercase tracking-widest text-stone">← Back to website</Link><p className="eyebrow">Account access</p><h2 className="mt-4 font-serif text-5xl">Welcome back.</h2><p className="mt-3 text-sm text-stone">Sign in to continue to your assigned workspace.</p><form onSubmit={submit} className="mt-10 space-y-5"><label><span>Email address</span><input name="email" type="email" autoComplete="email" required/></label><label><span>Password</span><input name="password" type="password" autoComplete="current-password" required/></label><div className="flex justify-end"><Link href="/forgot-password" className="text-xs text-forest underline">Forgot password?</Link></div>{error&&<p className="border-l-2 border-red-500 bg-red-50 p-3 text-sm text-red-700">{error}</p>}<button disabled={busy} className="btn-dark w-full">{busy?"Signing in…":"Sign in"}<Icon name="arrow" className="h-4 w-4"/></button></form></div></section></main>
}
