import {Footer} from "@/components/footer";import {AnimatedHeading} from "@/components/animated-heading";import {Header} from "@/components/header";import {ManagedPageHeader} from "@/components/managed-page-header";
export const metadata={title:"Privacy Policy"};
const sections=[
  ["Information we collect","We may collect contact details you provide through inquiries, meeting requests, applications, newsletter subscriptions, or other website forms. We also receive limited technical information such as browser type, device details, and general usage data."],
  ["How we use information","We use information to answer requests, provide property and service updates, improve our website and customer experience, operate our services, and send communications you have chosen to receive."],
  ["Cookies and analytics","Our website may use cookies and similar technologies for essential operation, preferences, performance measurement, and analytics. You can restrict cookies through your browser, although some website functions may then be unavailable."],
  ["How we protect information","We apply reasonable administrative and technical safeguards designed to protect personal information. No internet transmission or storage system is completely secure, so absolute security cannot be guaranteed."],
  ["Sharing information","We do not sell personal information. We may share only what is necessary with trusted service providers, professional advisers, authorities where legally required, or parties involved in a legitimate business transaction."],
  ["Your choices","You may ask to access, correct, or delete personal information where applicable, and you may unsubscribe from marketing communications at any time. Contact us to submit a privacy request."],
  ["Policy updates","We may revise this policy as our services or legal obligations change. The updated version will appear on this page with a revised effective date."],
];
export default function PrivacyPolicy(){return <><Header/><main className="inner-page privacy-page"><ManagedPageHeader contentKey="privacy-header" className="inner-page-hero" defaultLabel="About Raha" defaultTitle="Privacy Policy"/><section className="privacy-content"><div className="shell"><aside><span>Last updated</span><b>September 8, 2026</b><p>Questions about this policy?</p><a href="/contact-us">Contact our team</a></aside><article><p className="privacy-lead">This policy explains how Raha Holdings collects, uses, protects, and shares information when you use our website or contact our team.</p>{sections.map(([title,body],index)=><section key={title}><span>{String(index+1).padStart(2,"0")}</span><div><AnimatedHeading>{title}</AnimatedHeading><p>{body}</p></div></section>)}<section><span>08</span><div><AnimatedHeading>Property information disclaimer</AnimatedHeading><p>Renderings, plans, specifications, furniture, landscaping, and other visual materials are illustrative and may change during design or construction. They do not form a binding offer or agreement unless expressly included in signed contractual documents.</p></div></section></article></div></section></main><Footer/></>}
