import {AnimatedHeading} from "@/components/animated-heading";import {Header} from "@/components/header";import {Footer} from "@/components/footer";import {AboutSection} from "@/components/about-section";import {API_URL} from "@/lib/api";
type Block={id:string;key:string;block_type:string;title:string;body:string;image?:string;payload?:Record<string,unknown>};type Team={id:string;full_name:string;designation:string;department:string;biography:string;profile_image:string};type Data={content:Block[];team_members:Team[]};
const teamPortraits=["/images/team/executive-male.png","/images/team/executive-female.png"];
export const metadata={title:"About Us"};
async function load():Promise<Data>{try{const r=await fetch(`${API_URL}/home/`,{cache:"no-store"}),b=await r.json(),d=b.data||b;return{content:d.content||[],team_members:d.team_members||[]}}catch{return{content:[],team_members:[]}}}
export default async function AboutUs(){
  const data=await load(),get=(key:string)=>data.content.find(x=>x.key===key),header=get("about-header"),about=get("our-story"),mission=get("our-mission"),vision=get("our-vision"),values=get("company-values"),chairman=get("chairman-message"),items=Array.isArray(values?.payload?.items)?values.payload.items.map(String):[];
  return <><Header/><main className="about-page">{about?<><section className="about-page-hero" style={{backgroundImage:header?.image?`linear-gradient(90deg,rgba(0,31,61,.82),rgba(0,31,61,.18)),url(${header.image})`:about.image?`linear-gradient(90deg,rgba(0,31,61,.82),rgba(0,31,61,.18)),url(${about.image})`:undefined}}><div className="ref-container">{header?.body&&<p>{header.body}</p>}<AnimatedHeading as="h1">{header?.title||"About Us"}</AnimatedHeading></div></section><AboutSection pageMode about={{title:about.title,body:about.body,image:about.image,payload:about.payload as Record<string,string|number>}}/><section className="about-mission"><div className="ref-container"><div className="about-mission-grid"><article><small>01</small><p>Our</p><AnimatedHeading>Mission</AnimatedHeading><div>{mission?.body}</div></article><article><small>02</small><p>Our</p><AnimatedHeading>Vision</AnimatedHeading><div>{vision?.body}</div></article></div><div className="about-values"><p className="ref-kicker">What guides us</p><AnimatedHeading>{values?.title||"Our Values"}</AnimatedHeading><div>{items.map((item,i)=><article key={item}><b>{String(i+1).padStart(2,"0")}</b><h3>{item}</h3></article>)}</div></div></div></section>{chairman&&<><section className="about-chairman"><div className="ref-container"><div className="about-chairman-copy"><p className="ref-kicker">{String(chairman.payload?.role||"Chairman")}</p><AnimatedHeading>{chairman.title}</AnimatedHeading><p>{chairman.body}</p></div><div className="about-chairman-image"><img src={chairman.image||teamPortraits[0]} alt={chairman.title}/><span>{chairman.title}<small>{String(chairman.payload?.role||"")}</small></span></div></div></section><section className="about-chairman-bio"><div className="ref-container"><div className="about-bio-mark">ARCADIA<small>Leadership</small></div><div><p>{String(chairman.payload?.bio||chairman.body)}</p><blockquote>“We measure our success by the trust we earn and the quality of life our homes create.”</blockquote></div></div></section></>}<section className="about-team"><div className="ref-container"><p className="ref-kicker">Team</p><div className="about-team-heading"><AnimatedHeading>Management Team</AnimatedHeading><p>Experienced leaders united by a shared standard of quality, transparency, and customer care.</p></div><div className="about-team-grid">{data.team_members.map((member,index)=><article key={member.id}><img src={member.profile_image||teamPortraits[index%teamPortraits.length]} alt={member.full_name}/><div><h3>{member.full_name}</h3><p>{member.designation}</p></div></article>)}</div></div></section></>:<section className="grid min-h-[60vh] place-items-center"><p>About content is being prepared.</p></section>}</main><Footer/></>;
}
