# Generated by Django 5.2.17 on 2026-09-16 18:42

import common.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0004_contact_form_labels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='contact_form_image',
            field=models.ImageField(blank=True, upload_to='settings/contact/', validators=[common.validators.validate_image]),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='contact_hero_image',
            field=models.ImageField(blank=True, upload_to='settings/contact/', validators=[common.validators.validate_image]),
        ),
    ]
